name: focusify
description: A Flutter project for focus and productivity.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  firebase_storage: ^12.4.7
  firebase_ai: ^2.1.0
  do_not_disturb: ^1.0.3
  fluttericon: ^2.0.0
  google_sign_in: ^6.3.0
  firebase_analytics: ^11.5.0
  network_image_search: ^1.0.0
  google_nav_bar: ^5.0.7
  flutter_dotenv: ^5.2.1
  velocity_x: ^4.3.1
  wikipedia: ^0.0.8
  image_picker: ^1.1.2
  cloud_firestore: ^5.6.9
  youtube_player_flutter: ^9.1.1
  google_fonts: ^6.2.1
  toast: ^0.3.0
  brain_fusion: ^0.1.1
  gpt_markdown: ^1.0.20
  fl_chart: ^1.0.0
  markdown_widget: ^2.3.2+8
  flutter_markdown_plus: ^1.0.3
  flutter_tts: ^4.2.3
  flutter_local_notifications: ^19.2.1
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  permission_handler: ^12.0.0+1
  device_info_plus: ^11.5.0
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: League Spartan
      fonts:
        - asset: fonts/LeagueSpartan-Regular.ttf

    - family: Open Sans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
